name: Continuous Deployment

on:
    push: 
        branches: [ main ]

jobs:
    Docker_Deploynent:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN}}
            
            - name: Build, Tag and push image to DockerHub
              env: 
                DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                IMAGE_NAME: Wise_Clone_Nextjs_RTL_Cypress
              run:
                docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .
                docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

